name: Terraform Deployment

on:
  pull_request:
  push:
    branches:
      - main

env:
  TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_repository: ${{ github.repository }}
  TF_VAR_thumbnail: ${{ secrets.THUMBNAIL }}
  TERRAFORM_GITHUB_ACTIONS_ROLE_NAME: "GithubActionsRole"

permissions:
  id-token: write
  contents: read

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print AWS environment variables
        run: |
          echo "AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}"
          echo "Role to Assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.TERRAFORM_GITHUB_ACTIONS_ROLE_NAME }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::${{ env.TF_VAR_aws_account_id }}:role/${{ env.TERRAFORM_GITHUB_ACTIONS_ROLE_NAME }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Create terraform cache
        uses: actions/cache@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}

  terraform_check:
    runs-on: ubuntu-latest
    needs: terraform_init
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Terraform Format Check
        run: terraform fmt -check

  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.TERRAFORM_GITHUB_ACTIONS_ROLE_NAME }}

      - name: Terraform Plan
        run: terraform plan -input=false

  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.TERRAFORM_GITHUB_ACTIONS_ROLE_NAME }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
